channels:
- conda-forge
dependencies:
- python=3.10.15
- pip<=24.3.1
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.0
  - numpy==2.1.3
  - packaging==24.2
  - pandas==2.2.3
  - psutil==6.1.0
  - pyyaml==6.0.2
  - scikit-learn==1.5.2
  - scipy==1.14.1
name: mlflow-env
