name: split_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - requests
  - pip
  - pandas
  - scikit-learn
  - mlflow
  - pip:
      - wandb
      - databricks_cli
      - protobuf==3.20.3
